config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "pages#home"

  get "my_bookings", to: "pages#my_bookings"

  resources :animals, only: %i[index show new create edit update destroy] do
    resources :bookings, only: %i[new create]
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/animal.rb
class Animal < ApplicationRecord
  belongs_to :user
  has_many :bookings, dependent: :destroy
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?
  validates :name, presence: true
  validates :specie, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :origin, presence: true
  has_many_attached :images
  include PgSearch::Model
  pg_search_scope :search_by_specie_and_origin,
  against: %i[specie origin],
  using:
  {
    tsearch: { prefix: true }
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :animal
  validates :arrival_date, presence: true
  validates :end_date, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :bookings
  has_many :animals
  validates :username, presence: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

end

app/controllers/animals_controller.rb
class AnimalsController < ApplicationController
  before_action :set_animals, only: %i[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[show index]

  def index
    @animals = Animal.all
    @markers = @animals.geocoded.map do |animal|
      {
        lat: animal.latitude,
        lng: animal.longitude,
        info_window: render_to_string(partial: "info_window", locals: { animal: animal }),
        image_url: helpers.asset_url("/app/assets/images/logo.png")
      }
    end
      if params[:query].present?
        @animals = policy_scope(Animal.search_by_specie_and_origin(params[:query]))
      else
        @animals = policy_scope(Animal)
      end
  end

  def show
    authorize @animal
    @booking = Booking.new
  end

  def new
    @animal = Animal.new
    authorize @animal
  end

  def create
    @animal = Animal.new(animal_params)
    @animal.user = current_user
    authorize @animal
    if @animal.save
      redirect_to animals_path, notice: "animal was successfully created"
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    authorize @animal
  end

  def update
    authorize @animal
    if @animal.update(animal_params)
      redirect_to animal_path(@animal), notice: "animal was successfully updated"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    authorize @animal
    @animal.destroy
    redirect_to animals_path, notice: 'animal was successfully destroyed'
  end

  private

  def set_animals
    @animal = Animal.find(params[:id])
  end

  def animal_params
    params.require(:animal).permit(:name, :specie, :description, :price, :origin, :stock, :address, images: [])
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # [...]
  before_action :configure_permitted_parameters, if: :devise_controller?
  before_action :authenticate_user!
  include Pundit::Authorization

  # Pundit: allow-list approach
  after_action :verify_authorized, except: :index, unless: :skip_pundit?
  after_action :verify_policy_scoped, only: :index, unless: :skip_pundit?

  # Uncomment when you *really understand* Pundit!
  # rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized
  # def user_not_authorized
  #   flash[:alert] = "You are not authorized to perform this action."
  #   redirect_to(root_path)
  # end

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:username])
  end

  private

  def skip_pundit?
    devise_controller? || params[:controller] =~ /(^(rails_)?admin)|(^pages$)/
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def create
    @animal = Animal.find(params[:animal_id])
    @booking = Booking.new(booking_params)
    @booking.animal = @animal
    @booking.user = current_user
    authorize @booking

    if @booking.save
      redirect_to my_bookings_path
    else
      render "animals/show", status: :unprocessable_entity
    end
  end

  private

  def set_animal
    @animal = Animal.find(params)
  end

  def booking_params
    params.require(:booking).permit(:arrival_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  skip_before_action :authenticate_user!, only: :home
  def home
  end

  def my_bookings
    @bookings = current_user.bookings
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      redirect_to root_path, notice: 'User was successfully created' # TO CHANGE !!!!!!
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to root_path, notice: 'User was updated' # TO CHANGE !!!!!!
    else
      render :edit, status: :unprocessable_entity
    end
  end

  private

  def user_params
    params.require(:user).permit(:email, :password, :username, :firstname, :lastname, :user_type)
  end
end

app/helpers/animal_helper.rb
module AnimalHelper
  def cloudinary_image(animal, tagclass)
    if animal.images.attached?
      cl_image_tag animal.images[0].key, class: tagclass
    else
      image_tag "https://cdn.britannica.com/22/125622-050-E4DA94ED/Albino-axolotl.jpg", class: 'card-img-top animal-photo'
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/animals/_info_window.html.erb
<h2 class="h2popup"><%= animal.name %></h2>

  <div class="row" >
    <div class="col-3">
      <div class="popupcards">
        <%= cloudinary_image(animal, 'imagepopup')  %>
        <div class="card-body">
          <p class="text-center"> <%= animal.specie %>
          <p><%= link_to "More details", animal_path(animal), class:'aleluia'%></p>
        </div>
      </div>
    </div>
</div>

app/views/animals/edit.html.erb
<div class="edit-animal-card my-5">
  <div class="container">

  <h1 class="text-center">Edit your <%= @animal.name %></h1>

 <%= simple_form_for [@animal] do |f|  %>
    <%= f.input :name %>
    <%= f.input :specie %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :origin %>
    <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
    <%= f.input :stock %>
    <%= f.input :images, :input_html => { :multiple => true }%>
    <%= f.submit  class: "btn btn-success text-light"%>
  <% end %>
  </div>
</div>

app/views/animals/index.html.erb
<div class="container">
  <div class="text-center m-4 p-4">
    <h1 class="index-title">Here are all the animals available to rent 🐲</h1>
  </div>

<div class = "container m-5">
  <p>Do you want to rent your animals so other people can give them some love ? 💚</p>
  <%= link_to "Rent your animal", new_animal_path, class:'btn btn-flat'%>
</div>

<div class="index-container">
  <div class="cards-index-page">
    <% @animals.each do |animal| %>
      <div class="col">
        <div class="card-index-page">

          <%= cloudinary_image(animal, "card-img-top animal-photo") %>
          <div class="card-body ms-3 mt-3">
            <div>
            <h5 class="card-title"> <%= animal.name %></h5>
              <p class="card-text"> <%= animal.specie %> from <%= animal.origin %></p>
              <%= link_to "Rent it for €#{animal.price}", animal_path(animal), class:'btn-flat'%>
          </div>
          </div>
        </div>
      </div>
    <% end %>
  </div>

    <img id="map" src='https://api.mapbox.com/styles/v1/mapbox/streets-v11/static/2.3381,48.8693,10.45,0,0/600x1000?access_token=pk.eyJ1Ijoiem9ldmFucCIsImEiOiJjbGF1eTZzNm8wMGc4M3dvNXV6bWc0bzQwIn0.xejCp7-6FFay-8S02eOIlw'>

</div>


  <div>
  <%= link_to "Learn More", new_user_registration_path, class: "btn btn-flat" %>
</div>

app/views/animals/new.html.erb
<div class="new-animal-card my-5">
  <div class="container">

  <h1 class="text-center">Add an animal</h1>

  <%= simple_form_for [@animal] do |f|  %>
    <%= f.input :name %>
    <%= f.input :specie %>
    <%= f.input :description %>
    <%= f.input :price %>
    <%= f.input :origin %>
    <%= f.input :address,
      input_html: {data: {address_autocomplete_target: "address"}},
      wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}}
    %>
    <%= f.input :stock %>
    <%= f.input :images, :input_html => { :multiple => true }%>
    <%= f.submit  class: "btn btn-success text-light"%>
  <% end %>
  </div>
</div>

app/views/animals/show.html.erb
<div class= "container">
  <div class="container">
    <div class = "text-center m-3">
      <h1> Rent <%= @animal.name %> 🌿 </h1>
      <h2 class="showh2 p-4"> <strong> a wonderful <%= @animal.specie %> from <%= @animal.origin %></strong></h2>
    </div>
    <div class="container">
      <div class="row my-5">
      <% i = @animal.images.length - 1 %>
      <% while i >= 0 %>
        <div class="col-12 col-lg-4 col-md-12 my-3"> <%=cl_image_tag @animal.images[i].key, width: 350, height: 350, class: "imageee"%></div>
      <% i -= 1 %>
      <% end %>
      </div>

    </div>



    <div class="container py-5 px-4">
      <% if policy(@animal).edit? %>
        <p>This is your animal, do you want to edit or delete it?</p>
        <p><%= link_to "Edit", edit_animal_path(@animal), class: "btn-flat"%></p>
        <%= button_to "Destroy this Animal", @animal, class:'btn-flat', method: :delete if policy(@animal).destroy?%>
      <% end %>
    </div>

    <div class="container mt-5">
      <div class=" container mt-4">
        <div class="container mb-4 d-flex">
          <div class="details my-4  col-12 col-lg-4 col-sm-12">
            <h5 class="h5show">Description of the animal 🦚</h5>
            <hr>
              <p class="justifyshow"><%= @animal.description %></p>
            <h5>Price 💸</h5>
              <p><%= @animal.price %>€</p>
          </div>
          <div class="col-12 col-lg-8 mt-4 mx-5 px-3">
            <h5 class="h5show">How cute? And it can be yours...</h5>
            <hr>
              <%= simple_form_for [@animal, @booking], data: { turbo: false,controller: 'flatpickr' } do |f| %>
                <div class="form-label my-4 mb-5">
                  <%= f.input :arrival_date, as: :string, input_html: { data: { flatpickr_target: "arrivalTime" } }%>
                  <%= f.input :end_date, as: :string, input_html: { data: { flatpickr_target: "endTime" }, id:'end_time' } %>
                <div>
                  <%= f.submit class: "btn-flat" %>
                    </div>
                </div>
            <% end %>
            <p>⚡️ Hurry up ! <%= @animal.user.username %> only has <%= @animal.stock %> <%= @animal.specie %> left ⚡️</p>
          </div>
        </div>
      </div>
    </div>

  <div class="d-flex justify-content-between">
    <p><%= link_to "Back to list", animals_path, class:"btn-flat" %></p>

    <p><%= link_to "Back to main page", root_path, class: "btn-flat" %></p>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Exopetnet</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.css" rel="stylesheet">
    <script src="https://api.mapbox.com/mapbox-gl-js/v2.11.0/mapbox-gl.js"></script>
  </head>

  <body style="min-height: 100vh; position: relative">
    <%= render "/shared/navbar"  %>
    <%= render "/shared/flashes" %>
    <main id="main-content">
      <%= yield %>
    </main>
    <%= render "/shared/footer" %>
  </body>
</html>

app/views/pages/_cardbanner.html.erb
<div class="container justify-content-between">
  <div class="row">
      <div class="col">
        <div class="home-card">
          <img src="<%= %w(https://www.rd.com/wp-content/uploads/2020/05/GettyImages-143405634-scaled.jpg?resize=1536,1022
            https://www.rd.com/wp-content/uploads/2020/05/GettyImages-988272970-scaled.jpg?resize=1536,1022
            https://www.rd.com/wp-content/uploads/2020/05/GettyImages-164464932-scaled.jpg?resize=1536,1022
            https://www.rd.com/wp-content/uploads/2020/05/GettyImages-548004897-scaled.jpg?resize=1536,1222
            https://www.rd.com/wp-content/uploads/2021/04/GettyImages-158050945.jpg?resize=1536,1024).sample %>)" >
          <h4>Find Happiness with Animals</h4>
          <p>Phasellus a est in lacus pharetra viverra vitae at nunc. Suspendisse suscipit eleifend dui sed facilisis.<p>
          <div>
            <% if current_user %>
            <%= link_to "Go to all bookings", my_bookings_path, class: "btn-flat"%>
            <% else %>
              <%= link_to "Create an Account", new_user_registration_path, class: "btn-flat" %>
            <% end %>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="home-card">
          <img src="<%= %w(https://images.unsplash.com/photo-1526226060519-126d75eaa5e2?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2069&q=80
            https://images.unsplash.com/photo-1591630866811-eceedf667541?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1673&q=80
            https://www.rd.com/wp-content/uploads/2020/05/GettyImages-842822220-scaled.jpg?resize=1536,1024
            https://www.rd.com/wp-content/uploads/2021/04/GettyImages-691507732-scaled.jpg?resize=1536,1024).sample %>)" >
          <h4>We Love Fluffers As Much As You</h4>
          <p>Sed vel iaculis sapien. Nullam vel nunc odio. Ut nulla leo, condimentum ac ex fringilla, volutpat scelerisque risus.<p>
          <div>
            <% if current_user %>
                <%= link_to "Post an Animal", new_animal_path, class: "btn-flat" %>
              <% else %>
                <%= link_to "See all Animals", animals_path, class:"btn-flat" %>
            <% end %>
          </div>
        </div>
      </div>
        <div class="col">
        <div class="home-card">
          <img src="<%= %w(https://images.unsplash.com/photo-1442689859438-97407280183f?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2070&q=80
          https://images.unsplash.com/photo-1535338134198-e28df7d54e3d?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=2033&q=80
          https://www.rd.com/wp-content/uploads/2021/04/GettyImages-826981110-scaled.jpg?resize=1536,1018
          https://www.rd.com/wp-content/uploads/2021/04/GettyImages-182874101-1-scaled.jpg?resize=1536,1024
          https://www.rd.com/wp-content/uploads/2021/04/GettyImages-669723166-scaled-e1618242211739.jpg?resize=1536,1536).sample %>)" >
          <h4>Environmentally Friendly</h4>
          <p>Sed non turpis in elit elementum hendrerit. Pellentesque vestibulum nisl in tortor rutrum, sit amet gravida felis aliquam.<p>
            <div>
              <% if current_user %>
                <%= link_to "Learn More", new_user_registration_path, class: "btn-flat" %>
              <% else %>
                <%= link_to "Learn More", new_user_registration_path, class: "btn-flat" %>
              <% end %>
            </div>
        </div>
      </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/_carousel.html.erb
<div id="carouselExampleCaptions" class="carousel slide banner-carousel" data-bs-ride="carousel">
  <div class="carousel-indicators">
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="0" class="active" aria-current="true" aria-label="Slide 1"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="1" aria-label="Slide 2"></button>
    <button type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide-to="2" aria-label="Slide 3"></button>
  </div>
  <div class="carousel-inner">
    <div class="carousel-item active">
      <img class="img" src="https://wallpaper.dog/large/5441319.jpg" class="d-block w-100" alt="first slide red panda">
      <div class="carousel-caption carousel-options top-tagline">
        <div class="info">
          <h1>ExoPetNet</h1>
          <p>Rent an Exotic Animal to Love and Brighten your Days!</p>
        </div>
      </div>

    </div>
    <div class="carousel-item">
      <img class="img" src="https://i.dailymail.co.uk/i/pix/2012/04/06/article-0-127D0194000005DC-909_964x637.jpg" alt="Second slide baby seal" class="d-block w-100">
      <div class="carousel-caption carousel-options carousel-color-black top-tagline">
        <div class="info">
          <h1>Post Your Animal to Rent</h1>
          <p>Help Others Spend Time with Your Furry Friend</p>
        </div>
      </div>
    </div>
    <div class="carousel-item">
      <img class="img" src="https://image.winudf.com/v2/image/Y29tLk1vYmlsZVN0cmFuZ2VyLmFwcDA0NzBfc2NyZWVuXzJfMTUzODQyODEzNF8wOTc/screen-2.jpg?fakeurl=1&type=.webp" alt="Third slide baby cheetah" class="d-block w-100">
      <div class="carousel-caption carousel-options top-tagline">
        <div class="info">
          <h1>Create an Account with Us to Start Today</h1>
          <p>Click Below to Start Your Animal Journey</p>
        </div>
      </div>
    </div>
  </div>
  <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Previous</span>
  </button>
  <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleCaptions" data-bs-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="visually-hidden">Next</span>
  </button>
</div>

app/views/pages/_jumboabout.html.erb
<div class="jumbotron jumbotron-fluid">
  <div class="container text">
    <h1 class="display-4 text-center">About ExoPetNet</h1>
    <div class="container jumbo">
        <div class="item">
          <p class="line-content"><i class="fa-solid fa-hippo fa-xl">  </i> We are in the business of helping people find happiness and peace by spending time with animals.</p>
        </div>
        <div class="item">
          <p class="line-content"><i class="fa-solid fa-otter fa-xl">  </i> Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aenean eu mauris a elit varius malesuada.</p>
        </div>
        <div class="item">
        <p class="line-content"><i class="fa-solid fa-horse fa-xl">  </i> Vivamus imperdiet tellus sollicitudin gravida finibus. Cras nec nisl eu ex blandit bibendum.</p>
        </div>
        <div class="item">
        <p class="line-content"><i class="fa-solid fa-crow fa-xl">  </i> Phasellus et enim leo. Etiam quis vulputate sem. Vestibulum sed eros erat.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<br>
<%= render 'carousel' %>
<br>
<div class="cardstitle-container">
  <h1>See How ExoPetNet Can Help You</h1>
</div>
<br>
<%= render 'cardbanner' %>
<br>
<%= render 'jumboabout' %>

app/views/pages/my_bookings.html.erb
<div class="container">
  <br>
  <h1 class="bookingsh1">My Bookings</h1>
  <br>
  <% @bookings.each do |booking| %>
    <div class="mybookings_combined">
    <%= link_to animal_path(booking.animal_id), class: "booking-link row individual-booking p-0" do %>
      <div class="booking-text col-6 m-0" style="padding-right: 5%; padding-left: 5%">
        <h1><%= booking.animal.name %></h2>
        <hr>
        <p class="bookings-p">Arrival date: <%= booking.arrival_date %></p>
        <p class="bookings-p">Departure date: <%= booking.end_date %></p>
      </div>
      <div class="col-6 p-0">
        <%= cloudinary_image(booking.animal, 'image-container-booking')  %>
      </div>
    <% end %>
    </div>
  <% end %>
</div>

app/views/shared/_card-home.html.erb
<%=link_to animal_path(animal), class: "text-decoration-none" do %>
  <div class="index-animal-card">
    <%= cl_image_tag animal.image.key %>
    <div class="index-animal-card-infos">
      <h2>
        <%= animal.name %>
      </h2>
      <p>
        <%= animal.description %>
      </p>
    </div>
  </div>
<% end %>

app/views/shared/_card-index.html.erb
<%= link_to animal_path(animal), class: "text-decoration-none" do %>
  <div class="card-category position-relative">
    <%= cl_image_tag animal.images[0].key %>
    <%= animal.name %>
     <p class="position-absolute tag-price m-0"><%= animal.price %> €</p>
      <p class="position-absolute tag-origin m-0"><%= animal.origin %></p>
    </div>
    <div>
      <p class="card-description"><strong>About:</strong> <%= animal.description %></p>
    </div>
  </div>
<% end %>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-copyright">
    This footer is made with <i class="fas fa-heart"></i> at Le Wagon © 2022
  </div>
  <div class="footer-links">
    <%= link_to "Home", root_path %>
    <%= link_to "All Animals", animals_path %>
    <% if current_user%>
      <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete} %>
    <% else %>
      <%= link_to "Sign up", new_user_session_path %>
    <% end %>

  </div>
</div>

app/views/shared/_navbar.htm.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <div class="container-fluid">
    <%= link_to "#", class: "navbar-brand" do %>
      <%= image_tag "https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/logo.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <%# if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Home", "#", class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Messages", "#", class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "https://kitt.lewagon.com/placeholder/users/ssaunier", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "Action", "#", class: "dropdown-item" %>
              <%= link_to "Another action", "#", class: "dropdown-item" %>
              <%= link_to "Log out", "#", class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <%# else %>
          <!--li class="nav-item"-->
            <%#= link_to "Login", new_user_session_path, class: "nav-link" %>
          <!--/li-->
        <%# end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon mt-3">
  <div class="container-fluid ms-3">
      <%= link_to "<i class='fa-solid fa-paw'>ExoPetNet</i>".html_safe, root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <%= form_with url: animals_path, method: :get, class: "d-flex" do %>
  <%= text_field_tag :query,
    params[:query],
    class: "form-control me-2",
    placeholder: "Find your dream pet"
  %>
  <%= submit_tag "Search", class: "btn btn-light" %>
<% end %>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <li class="nav-item">
          <a class="nav-link" href="/animals">All Animals</a>
        </li>
        <% if user_signed_in? %>
        <li class="nav-item active">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
        <div class="nav-link">
          <strong>Hi</strong> <%= current_user.username if user_signed_in? %>
        </div>
        </li>
        <li class="nav-item dropdown">
          <img class="avatar dropdown-toggle me-3" id="navbarDropdown" data-bs-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/random" />
        <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
            <%= link_to "Profile", my_bookings_path , class: "dropdown-item"  %>
            <%= link_to "Add Animal", new_animal_path, class: "dropdown-item"  %>

            <%= link_to "My Bookings", my_bookings_path, class: "dropdown-item" %>
            <%= link_to "Log out", destroy_user_session_path, data: {turbo_method: :delete}, class: "dropdown-item" %>
        </div>
        </li>
        <% else %>
        <li class="nav-item dropdown">
          <div class="d-flex flex-direction-row">
            <%= link_to "Login", new_user_session_path, class: "btn btn-outline-success mx-2" %>
            <%= link_to "Sign up", new_user_registration_path, class: "btn btn-success text-light" %>
          </div>
        </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>